/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cazzendra.pos.ui;

import cazzendra.pos.control.CommonController;
import cazzendra.pos.core.Loading;
import cazzendra.pos.model.student;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.KeyStroke;

/**
 *
 * @author Amal
 */
public class MainMenuV3 extends javax.swing.JFrame {

    private String Lang;
    boolean PaidStatus = false;

    int StudentId = 0;
    student Student = null;

    /**
     * @param Language
     */
    public MainMenuV3(String Language) {
        initComponents();
        this.Lang = Language;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();
        lblDateTime.setText(dtf.format(now));
        panel.setBackground(Loading.getColorCode());
        lblLoggedUser.setText(Loading.getUser().getUserName());
        HotKeys();
    }
    
    private void HotKeys() {
        KeyStroke ks = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        InputMap im = btnCloseApp.getInputMap(JButton.WHEN_IN_FOCUSED_WINDOW);
        im.put(ks, "C");
        btnCloseApp.getActionMap().put("C", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        lblCopyrightStatement = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblLoggedUser = new javax.swing.JLabel();
        lblnamePriceUpdate2 = new javax.swing.JLabel();
        btnCloseApp = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance");
        setBackground(new java.awt.Color(0, 0, 102));
        setMinimumSize(new java.awt.Dimension(1368, 718));
        setResizable(false);
        setSize(new java.awt.Dimension(1368, 718));

        panel.setMaximumSize(new java.awt.Dimension(1360, 600));
        panel.setMinimumSize(new java.awt.Dimension(1360, 600));
        panel.setPreferredSize(new java.awt.Dimension(1360, 600));

        lblCopyrightStatement.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        lblCopyrightStatement.setForeground(new java.awt.Color(0, 0, 102));
        lblCopyrightStatement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyrightStatement.setText("######");

        jLabel25.setFont(new java.awt.Font("Ubuntu Medium", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Logged As ");

        lblLoggedUser.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        lblLoggedUser.setForeground(new java.awt.Color(255, 0, 0));
        lblLoggedUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoggedUser.setText("User Name");
        lblLoggedUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoggedUserMouseClicked(evt);
            }
        });

        lblnamePriceUpdate2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblnamePriceUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        lblnamePriceUpdate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/ui/icons/logged_user.png"))); // NOI18N
        lblnamePriceUpdate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnamePriceUpdate2MouseClicked(evt);
            }
        });

        btnCloseApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cazzendra/pos/newtheme/icons/exit-button-40x40.png"))); // NOI18N
        btnCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseAppMouseClicked(evt);
            }
        });

        lblDateTime.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(0, 0, 102));
        lblDateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTime.setText("2020-01-14");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(817, 817, 817)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel25))
                            .addComponent(lblLoggedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(lblnamePriceUpdate2)
                        .addGap(46, 46, 46)
                        .addComponent(btnCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCopyrightStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel25)
                        .addGap(6, 6, 6)
                        .addComponent(lblLoggedUser))
                    .addComponent(lblnamePriceUpdate2)
                    .addComponent(btnCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(lblCopyrightStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoggedUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoggedUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoggedUserMouseClicked

    private void lblnamePriceUpdate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnamePriceUpdate2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblnamePriceUpdate2MouseClicked

    private void btnCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseAppMouseClicked
        try {
            boolean status = CommonController.Activation();
            if (status) {
                try {
                    CommonController.AutoBackupDB();
                } catch (URISyntaxException | IOException | InterruptedException ex) {
                    Logger.getLogger(MainMenuV3.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Login().setVisible(true);
                this.dispose();
            } else {
                new ActivationUI().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuV3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCloseAppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuV3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuV3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuV3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuV3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuV3("test param").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCloseApp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel lblCopyrightStatement;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblnamePriceUpdate2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
